### ISSUE TITLE
collision callback is not called

### ISSUE THREAD

**Issue by jonascarpay** [jonascarpay/apecs-physics#1]
I'm having some trouble with inline-c function pointers [here](https://github.com/jonascarpay/phycs/blob/08b2ba30b4c6915755aba503477ec00f89a6e58d/src/Apecs/Physics/Collision.hs#L55).
It seems like my function is never actually called, even though it is allocated and and I get a runtime error if I change the field to NULL.
If also seems like the default function is not being called (printf doesnt trigger), so what is returning 1 for the collision to be accepted?

**Comment by gelisam** [comment]
I was about to tell you that inline-c calls [`freeHaskellFunPtr`](https://wiki.haskell.org/Foreign_Function_Interface#Function_pointers) at the end of the block and thus your function pointer is no longer valid when chipmunk calls it later on, but I guess you've since figured it out!

When I tried to write a small self-contained example reproducing the issue, I got a crash when I tried to call the function pointer. In your codebase it fails silently instead, I don't know why.

**Comment by jonascarpay** [comment]
That's weird, I ended up trying a number of different GHC's, and every time the function returned garbage. Which is particularly nasty because I thought it was returning 1..

**Comment by LukaHorvat** [comment]
So how did you solve it?

**Comment by jonascarpay** [comment]
I switched to manually making a `FunPtr`, but now I'm getting an `internal error: stg_ap_p_ret` whenever the callback is triggered, and I haven't I haven't had time to really look into that yet. You should be able to reproduce that error by checking out the `collision_callback` branch and running the `platform` executable
